# Scan papers and update papers.js + generate missing thumbnails.
# Usage:
#   Run this from PowerShell, or double-click if .ps1 is associated with PowerShell.
# What it does:
#   1) Walks assets/papers/<category>/*.png
#   2) Writes assets/papers.js (a list of {slug, items} consumed by index.html)
#   3) For each PNG without a thumb at assets/papers-thumb/<category>/<name>.jpg,
#      generates a 320px JPEG q70 thumbnail using .NET System.Drawing.

$ErrorActionPreference = 'Stop'

$root      = Split-Path -Parent $MyInvocation.MyCommand.Path
$papersDir = Join-Path $root 'assets\papers'
$thumbDir  = Join-Path $root 'assets\papers-thumb'
$outFile   = Join-Path $root 'assets\papers.js'

if (-not (Test-Path $papersDir)) { throw "papers dir not found: $papersDir" }
if (-not (Test-Path $thumbDir))  { New-Item -ItemType Directory -Path $thumbDir | Out-Null }

Add-Type -AssemblyName System.Drawing

function Parse-PaperBase {
    param([string]$name)
    $num = -1
    $side = 0
    if ($name -match '(\d+)') { $num = [int]$matches[1] }
    if ($name -match '[Rr]$') { $side = 1 }
    [PSCustomObject]@{ Num = $num; Side = $side; Name = $name }
}

function Make-Thumb {
    param([string]$srcPng, [string]$dstJpg)
    if (Test-Path $dstJpg) { return $false }
    $dir = Split-Path -Parent $dstJpg
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir | Out-Null }
    $img = [System.Drawing.Image]::FromFile($srcPng)
    try {
        $w = 320
        $h = [int][Math]::Round($img.Height * ($w / $img.Width))
        $bmp = New-Object System.Drawing.Bitmap($w, $h)
        try {
            $g = [System.Drawing.Graphics]::FromImage($bmp)
            $g.InterpolationMode  = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
            $g.SmoothingMode      = [System.Drawing.Drawing2D.SmoothingMode]::HighQuality
            $g.PixelOffsetMode    = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
            $g.CompositingQuality = [System.Drawing.Drawing2D.CompositingQuality]::HighQuality
            $g.DrawImage($img, 0, 0, $w, $h)
            $g.Dispose()
            $codec = [System.Drawing.Imaging.ImageCodecInfo]::GetImageEncoders() | Where-Object { $_.MimeType -eq 'image/jpeg' }
            $params = New-Object System.Drawing.Imaging.EncoderParameters(1)
            $params.Param[0] = New-Object System.Drawing.Imaging.EncoderParameter([System.Drawing.Imaging.Encoder]::Quality, [long]70)
            $bmp.Save($dstJpg, $codec, $params)
            return $true
        } finally { $bmp.Dispose() }
    } finally { $img.Dispose() }
}

$cats = @()
$newThumbs = 0
$totalPapers = 0

$dirs = Get-ChildItem -Path $papersDir -Directory | Sort-Object Name
foreach ($d in $dirs) {
    $pngs = Get-ChildItem -Path $d.FullName -Filter '*.png' -File
    if ($pngs.Count -eq 0) { continue }
    $parsed = $pngs | ForEach-Object {
        $info = Parse-PaperBase $_.BaseName
        $info | Add-Member -NotePropertyName FullName -NotePropertyValue $_.FullName -PassThru
    }
    $sorted = $parsed | Sort-Object Num, Side, Name
    $names = @($sorted | ForEach-Object { $_.Name })
    $minN  = ($parsed | Measure-Object Num -Minimum).Minimum
    $cats += [PSCustomObject]@{
        Slug   = $d.Name
        MinNum = $minN
        Items  = $names
    }
    $totalPapers += $names.Count
    foreach ($p in $sorted) {
        $thumbPath = Join-Path $thumbDir (Join-Path $d.Name ($p.Name + '.jpg'))
        $created = Make-Thumb -srcPng $p.FullName -dstJpg $thumbPath
        if ($created) {
            $newThumbs++
            Write-Host ("  + thumb " + $d.Name + "/" + $p.Name + ".jpg")
        }
    }
}

# Order categories by earliest page number, then by slug as tie-break.
$ordered = $cats | Sort-Object @{Expression='MinNum'; Ascending=$true}, Slug

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('// Auto-generated by scan-papers script. Do not edit by hand.')
$lines.Add('// To add a new paper: drop the PNG into assets/papers/<category>/ and re-run the script.')
$lines.Add('window.PAPERS = [')
foreach ($c in $ordered) {
    $itemStr = ($c.Items | ForEach-Object { "'" + $_ + "'" }) -join ', '
    $lines.Add("  { slug: '$($c.Slug)', items: [$itemStr] },")
}
$lines.Add('];')

$content = ($lines -join "`r`n") + "`r`n"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outFile, $content, $utf8NoBom)

Write-Host ""
Write-Host "Done."
Write-Host ("  categories: " + $ordered.Count)
Write-Host ("  papers:     " + $totalPapers)
Write-Host ("  new thumbs: " + $newThumbs)
Write-Host ("  output:     " + $outFile)
